In [1]:
import numpy as np

# Array sin outliers
data_normal = np.array([10, 12, 11, 13, 12, 14, 10, 11, 13])

# Array con outliers
data_outliers = np.array([10, 12, 1169, 13, 12, 14, 10, 11, 13, 2000])

## Medidas centrales de los datos sin grandes outliers

In [6]:
np.mean(data_normal)

np.float64(11.777777777777779)

In [7]:
np.median(data_normal)

np.float64(12.0)

## Medidas centrales de los datos con grandes outliers

In [8]:
np.mean(data_outliers)

np.float64(30.6)

In [9]:
np.median(data_outliers)

np.float64(12.0)

Se observa q en la lista de numeros con grandes outliers hay una diferencia notable entre ambas medidas

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('Housing.csv')

In [16]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [15]:
df.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [14]:
df.select_dtypes(include='object')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
0,yes,no,no,no,yes,yes,furnished
1,yes,no,no,no,yes,no,furnished
2,yes,no,yes,no,no,yes,semi-furnished
3,yes,no,yes,no,yes,yes,furnished
4,yes,yes,yes,no,yes,no,furnished
...,...,...,...,...,...,...,...
540,yes,no,yes,no,no,no,unfurnished
541,no,no,no,no,no,no,semi-furnished
542,yes,no,no,no,no,no,unfurnished
543,no,no,no,no,no,no,furnished
544,yes,no,no,no,no,no,unfurnished